#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Daniel Polo
"""Agent-runnable consistency lint for egl-utils-java (generated by EADOS).

A dependency-free (Python 3 standard library only) checker that asserts the project is
internally congruent after any change. Run from anywhere in the repo:

    python tools/consistency_lint.py

It exits non-zero with an actionable report when a congruence invariant is violated. The
contract (the "congruence checks"):

  1. version-lockstep — the version constant, the README `Status-vX.Y.Z` badge, and the
     latest released changelog/release file (if any) agree;
  2. adr-index       — every docs/adr/NNNN-*.md is indexed and every indexed ADR exists,
     with sequential numbering and no gap;
  3. patterns        — every Implemented/Planned catalogue row cites an existing ADR (either
     numbering scheme, ADR-0008) and an existing production source file under a reactor
     module's src/main/;
  4. spec-map        — the ROADMAP Spec Coverage Map has no dangling row;
  5. milestones      — README ↔ ROADMAP milestone-completion state is consistent and no
     checkbox is malformed;
  6. bugs            — every docs/bugs/ record has valid frontmatter, its filename/path
     agrees with its id/discovered date, ids are unique and non-gapped, the index ↔ files
     bijection holds, and a `fixed` record names its `fixed-in`;
  7. i18n-freshness  — (only when i18n is enabled) no translated page is staler than its
     English source.

Each check is independent; all run, then the report lists every failure. The checks are
designed to PASS on a freshly-generated repository (empty catalogues, no releases yet).

Generated configuration is in the CONFIG block below — EADOS fills it from project.yaml.
"""

import os
import re
import subprocess
import sys
import xml.etree.ElementTree as ET  # jpms-congruence reads the reactor POMs

# ---------------------------------------------------------------------------
# CONFIG — filled by EADOS at generation time from orchestrator/project.yaml.
# ---------------------------------------------------------------------------
# ITEM 1.1 / ADR-0003: both paths below were corrected by hand when the Maven reactor replaced the
# flat source tree. The renderer joins src_main with version_file, which for a
# build-manifest version resolves to a path that can never exist (src/main/.../pom.xml) — leaving
# version-lockstep to compare the README badge against itself and always pass. The parent POM is at
# the repo root, so version_file is now "pom.xml" and the check is real. src_main points at core's
# package root, per ADR-0003. A re-render reverts both; that divergence is ADR-0003's recorded cost.
CONFIG = {
    # The file holding the version constant, relative to the repo root, or None if the
    # version lives only in a build manifest the lint should not parse. When None (or the
    # file is absent), version-lockstep derives the source version from the README badge.
    "version_file": "pom.xml",
    # A regex with a single (\d+\.\d+\.\d+) group that extracts the version from that file.
    # ANCHORED to the <version> element: the rendered default r"(\d+\.\d+\.\d+)" is unanchored
    # and matches "maven-4.0.0.xsd" in the schemaLocation URL, which appears BEFORE the project
    # version — so it read 4.0.0 and failed against the badge. Fine for a Version.java constant,
    # wrong for an XML build manifest. <modelVersion> does not match: the pattern needs "<version>".
    "version_regex": r"<version>(\d+\.\d+\.\d+)</version>",
    # The source root that pattern code-locations must live under.
    "src_main": "d4np-core/src/main/java/it/d4np/utils",
    # Whether documentation i18n is enabled (gates check 7).
    "i18n_enabled": False,
}

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
failures = []  # list of (check_name, message)


def fail(check, message):
    failures.append((check, message))


def read(*parts):
    with open(os.path.join(ROOT, *parts), encoding="utf-8") as handle:
        return handle.read()


def exists(rel):
    return os.path.exists(os.path.join(ROOT, rel))


def git(*args):
    try:
        out = subprocess.run(
            ["git", "-C", ROOT, *args], capture_output=True, text=True, check=True
        )
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def semver_tuple(text):
    m = re.search(r"(\d+)\.(\d+)\.(\d+)", text)
    return tuple(int(g) for g in m.groups()) if m else None


# ---------------------------------------------------------------------------
# 1. Version lockstep
# ---------------------------------------------------------------------------
def check_version_lockstep():
    name = "version-lockstep"
    readme = read("README.md")
    bm = re.search(r"Status-v(\d+\.\d+\.\d+)", readme)
    if bm is None:
        fail(name, "no `Status-vX.Y.Z` badge found in README.md")
        return
    badge = bm.group(1)

    # Source of truth: the version file if present, else the badge itself.
    source = badge
    vf = CONFIG.get("version_file")
    if vf and exists(vf):
        text = read(*vf.split("/"))
        vm = re.search(CONFIG["version_regex"], text)
        if vm is None:
            fail(name, f"could not parse a version from {vf} with the configured regex")
            return
        source = vm.group(1)
        if badge != source:
            fail(name, f"README badge v{badge} != version file {vf} ({source})")

    # Latest released changelog file (per-version split), if any exist.
    cl_dir = os.path.join(ROOT, "docs", "changelog")
    cl = []
    if os.path.isdir(cl_dir):
        for cur, _d, files in os.walk(cl_dir):
            for fn in files:
                m = re.fullmatch(r"v(\d+\.\d+\.\d+)\.md", fn)
                if m:
                    cl.append(m.group(1))
    if cl:
        latest = max(cl, key=semver_tuple)
        if latest != source:
            fail(name, f"latest docs/changelog v{latest} != source version {source}")

    # Latest release-notes file, if any exist.
    rel_dir = os.path.join(ROOT, "docs", "releases")
    rel = []
    if os.path.isdir(rel_dir):
        for fn in os.listdir(rel_dir):
            m = re.fullmatch(r"v(\d+\.\d+\.\d+)\.md", fn)
            if m:
                rel.append(m.group(1))
    if rel:
        latest = max(rel, key=semver_tuple)
        if latest != source:
            fail(name, f"latest docs/releases/v{latest}.md != source version {source}")


# ---------------------------------------------------------------------------
# 2. ADR index bijection + sequential numbering + status congruence (both schemes)
# ---------------------------------------------------------------------------
# ITEM 1.10 / ADR-0008 extends this check in two directions.
#
# THE IMPORTED SET. This project's decisions were taken under two regimes, so ids come in two shapes:
# four-digit ids are records written under docs/adr/, three-digit ids are the four pre-governance
# decisions of 2026-07-14 that live in .spec/adr/ and are still binding (every module POM cites
# ADR-001). Item 1.10 chose to index those in place rather than renumber them — 183 references in 45
# files, plus a git history that cites the ids verbatim — so the index, not the directory, is what
# makes the record complete. This check is therefore what keeps that decision honest: without it the
# imported four are indexed by prose alone, and docs/adr/README.md is a GENERATED file whose renderer
# emits only the 0001/0002 rows, so a re-render silently shrinks the record back (risk R-07).
#
# STATUS CONGRUENCE, for both schemes. The check previously verified presence and numbering only, so
# an ADR marked `Superseded` in its own header could sit in the index as `Accepted` indefinitely —
# ADR-0002 is the live case. Only the leading clause is compared: the index says "Superseded by
# ADR-0003" where the record says "Superseded by [ADR-0003](0003-….md) (2026-07-27)", and demanding
# character equality there would force the index to restate provenance it has no room for.
_IMPORTED_ADR_DIR = (".spec", "adr")
_IMPORTED_ADR_RE = re.compile(r"d4np_java_adr_(\d{3})_[a-z0-9_]+\.md")


def _status_head(text):
    """Normalise a status to its leading clause: 'Accepted', 'Superseded by ADR-0003', …

    Markdown links are flattened to their label so `[ADR-0003](0003-….md)` compares equal to
    `ADR-0003`, and anything after an em dash, a parenthesis or a comma is provenance rather than
    status ("Accepted — drafted by the agent, accepted by the owner on 2026-07-26").
    """
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.split(r"[—(,]", text)[0]
    return " ".join(text.split()).rstrip(".").lower()


def check_adr_index():
    name = "adr-index"
    adr_dir = os.path.join(ROOT, "docs", "adr")
    if not os.path.isdir(adr_dir):
        fail(name, "docs/adr/ directory is missing")
        return
    files = sorted(fn for fn in os.listdir(adr_dir) if re.fullmatch(r"\d{4}-.+\.md", fn))
    if not files:
        fail(name, "no ADR files found (expected at least 0001 and 0002)")
        return
    index = read("docs", "adr", "README.md")
    # filename -> status cell. The two index tables differ in shape — a governed row carries its link
    # in the id cell, an imported row carries it in the "Record" cell and has five columns — so the
    # status cell is located by CONTENT (the first cell that reads as a status) rather than by
    # position, and the filename is taken from the link that identifies the row. Matching the id cell
    # for governed rows specifically matters: an imported row also links to the ADR that carried its
    # decision forward, and keying on every link in the row would let one row answer for another.
    governed_rows, imported_rows = {}, {}
    for row in re.findall(r"^\|.*\|$", index, re.MULTILINE):
        cells = [c.strip() for c in row.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        status = next(
            (
                c
                for c in cells
                if _status_head(c).startswith(("accepted", "superseded", "proposed", "deprecated"))
            ),
            None,
        )
        if status is None:
            continue
        id_link = re.search(r"\]\((\d{4}-[a-z0-9-]+\.md)\)", cells[0])
        if id_link:
            governed_rows[id_link.group(1)] = status
        for target in re.findall(r"\]\(([^)]+)\)", row):
            m = _IMPORTED_ADR_RE.search(target)
            if m:
                imported_rows[m.group(0)] = status

    for fn in files:
        if fn[:-3] not in index:
            fail(name, f"ADR '{fn[:-3]}' is not listed in docs/adr/README.md")
            continue
        body = read("docs", "adr", fn)
        fm = re.search(r"^-\s+\*\*Status:\*\*\s*(.+)$", body, re.MULTILINE)
        if fm is None:
            fail(name, f"{fn}: no '- **Status:** …' line to compare against the index")
        elif fn not in governed_rows:
            fail(name, f"{fn}: appears in docs/adr/README.md but not as an indexed row with a "
                       f"status cell")
        elif _status_head(governed_rows[fn]) != _status_head(fm.group(1)):
            fail(name, f"{fn}: index says status '{governed_rows[fn]}' but the record says "
                       f"'{fm.group(1).strip()}'")
    nums = [int(fn[:4]) for fn in files]
    for i, n in enumerate(nums, start=1):
        if n != i:
            fail(name, f"ADR numbering gap/dup: expected {i:04d}, found {n:04d}")
            break
    for num in re.findall(r"\]\((\d{4}-[a-z0-9-]+\.md)\)", index):
        if not os.path.exists(os.path.join(adr_dir, num)):
            fail(name, f"index links missing ADR file '{num}'")

    # --- the imported (three-digit) series ---------------------------------
    imported_dir = os.path.join(ROOT, *_IMPORTED_ADR_DIR)
    if not os.path.isdir(imported_dir):
        return  # a checkout without the intake area is not a congruence failure
    imported = sorted(fn for fn in os.listdir(imported_dir) if _IMPORTED_ADR_RE.fullmatch(fn))
    if not imported:
        fail(name, ".spec/adr/ exists but holds no d4np_java_adr_NNN_*.md record")
        return
    rel_prefix = "/".join(_IMPORTED_ADR_DIR)
    for fn in imported:
        num = _IMPORTED_ADR_RE.fullmatch(fn).group(1)
        if fn not in index:
            fail(name, f"imported ADR-{num} ({rel_prefix}/{fn}) is not listed in "
                       f"docs/adr/README.md — it is binding and cited from the POMs, so an index "
                       f"without it under-reports the record (ADR-0008)")
            continue
        body = read(*_IMPORTED_ADR_DIR, fn)
        tm = re.search(r"^#\s*ADR-(\d{3}):", body, re.MULTILINE)
        if tm is None:
            fail(name, f"{rel_prefix}/{fn}: no '# ADR-NNN: …' title to derive the id from")
        elif tm.group(1) != num:
            fail(name, f"{rel_prefix}/{fn}: title says ADR-{tm.group(1)} but the filename says "
                       f"{num}")
        sm = re.search(r"^\|\s*\*\*Status\*\*\s*\|\s*(.+?)\s*\|", body, re.MULTILINE)
        if sm is None:
            fail(name, f"{rel_prefix}/{fn}: no '| **Status** | … |' row to compare against the index")
        elif fn not in imported_rows:
            fail(name, f"{rel_prefix}/{fn}: linked from docs/adr/README.md but not from an indexed "
                       f"row carrying a status cell")
        elif _status_head(imported_rows[fn]) != _status_head(sm.group(1)):
            fail(name, f"{rel_prefix}/{fn}: index says status '{imported_rows[fn]}' but the record "
                       f"says '{sm.group(1)}'")
    inums = [int(_IMPORTED_ADR_RE.fullmatch(fn).group(1)) for fn in imported]
    for i, n in enumerate(inums, start=1):
        if n != i:
            fail(name, f"imported ADR numbering gap/dup: expected {i:03d}, found {n:03d}")
            break
    for target in re.findall(r"\]\(([^)]+d4np_java_adr_\d{3}_[a-z0-9_]+\.md)\)", index):
        if not os.path.exists(os.path.normpath(os.path.join(adr_dir, target))):
            fail(name, f"index links missing imported ADR file '{target}'")


# ---------------------------------------------------------------------------
# 3. Catalogued patterns -> ADR + code location (tolerant of an empty catalogue)
# ---------------------------------------------------------------------------
# ITEM 2.1 widened BOTH link vocabularies, because both were unsatisfiable in this repository and the
# first catalogue row to cite anything real is what exposed it. Until now every row read `_TBD_` /
# `_spec (intake)_` and carried `| — |` in its id column, so nothing was ever checked.
#
#   * ADR link — the rendered check accepted only `adr/NNNN-*.md`, the four-digit governed series.
#     The pattern this item lands, Result / Either, was decided by **ADR-002**: one of the four
#     pre-governance records that ADR-0008 deliberately KEPT in `.spec/adr/` under three-digit ids
#     rather than renumbering. Under the old regex the only way to pass was to cite an ADR that did
#     not make the decision — the check would have enforced a false citation.
#   * Code location — it accepted only a repo-root-relative `src/...` path, which ADR-0003's reactor
#     made unreachable: production code lives at `<module>/src/main/java/...`. A row citing a real
#     file therefore failed with "no source code location" whatever real file it cited. (Item 1.1
#     corrected CONFIG["src_main"] for the reactor but not this regex, which does not read CONFIG.)
#
# Both forms are accepted and both are resolved ON DISK, so a row still cannot cite a record or a file
# that does not exist. `src/main/` specifically: a design pattern the catalogue claims as Implemented
# is part of the published surface, so a location under a test or harness root is a miscategorised row
# rather than an implementation.
_ADR_LINK_GOVERNED = re.compile(r"\((?:\.\./)*adr/(\d{4}-[a-z0-9-]+\.md)\)")
_ADR_LINK_IMPORTED = re.compile(r"\((?:\.\./)*\.spec/adr/(d4np_java_adr_\d{3}_[a-z0-9_]+\.md)\)")
_CODE_LINK = re.compile(r"\((?:\.\./)*((?:[A-Za-z0-9_.-]+/)?src/main/[A-Za-z0-9_./-]+)\)")


def check_patterns():
    name = "patterns"
    if not exists("docs/patterns/README.md"):
        fail(name, "docs/patterns/README.md is missing")
        return
    cat = read("docs", "patterns", "README.md")
    # Real Implemented/Planned rows start with `| <digits> |`. The `| — |` placeholder row is
    # ignored, so a freshly-generated empty catalogue passes.
    rows = re.findall(r"^\|\s*\d+\s*\|.*\|.*$", cat, re.MULTILINE)
    catalogued = [r for r in rows if "Implemented" in r or "Planned" in r]
    for row in catalogued:
        pattern = row.split("|")[2].strip()
        governed = _ADR_LINK_GOVERNED.findall(row)
        imported = _ADR_LINK_IMPORTED.findall(row)
        if not governed and not imported:
            fail(name, f"pattern '{pattern}': no ADR link in its row — expected "
                       f"docs/adr/NNNN-*.md or .spec/adr/d4np_java_adr_NNN_*.md (both series are "
                       f"binding; the digit count is semantic, ADR-0008)")
        for adr in governed:
            if not exists(os.path.join("docs", "adr", adr)):
                fail(name, f"pattern '{pattern}': ADR '{adr}' does not exist")
        for adr in imported:
            if not exists(os.path.join(".spec", "adr", adr)):
                fail(name, f"pattern '{pattern}': imported ADR '{adr}' does not exist")
        code = _CODE_LINK.findall(row)
        if not code:
            fail(name, f"pattern '{pattern}': no source code location in its row — expected a path "
                       f"under <module>/src/main/ (ADR-0003 reactor layout)")
        for path in code:
            if not exists(path):
                fail(name, f"pattern '{pattern}': code location '{path}' does not exist")


# ---------------------------------------------------------------------------
# 4. Spec Coverage Map — no dangling row
# ---------------------------------------------------------------------------
def check_spec_map():
    name = "spec-map"
    roadmap = read("ROADMAP.md")
    block = re.search(r"## Spec Coverage Map.*?(?=\n## |\Z)", roadmap, re.DOTALL)
    if block is None:
        fail(name, "no '## Spec Coverage Map' section in ROADMAP.md")
        return
    glyphs = {"⏳", "🚧", "✅", "❎"}
    seen = 0
    for line in block.group(0).splitlines():
        if not line.startswith("| §"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 4:
            fail(name, f"malformed Spec Coverage Map row: {line.strip()}")
            continue
        seen += 1
        section, items, status = cells[0], cells[2], cells[3]
        if not items:
            fail(name, f"spec row {section} has an empty 'Roadmap items' cell (dangling)")
        if not any(g in status for g in glyphs):
            fail(name, f"spec row {section} has no recognised status glyph: '{status}'")
    if seen == 0:
        fail(name, "Spec Coverage Map has no '| §...' rows")


# ---------------------------------------------------------------------------
# 5. ROADMAP <-> README milestone completion consistency
# ---------------------------------------------------------------------------
def check_milestones():
    name = "milestones"
    readme = read("README.md")
    roadmap = read("ROADMAP.md")
    readme_status = {}
    for m in re.finditer(r"^\|\s*(\d+)\s*\|[^|]+\|\s*([^|]+?)\s*\|$", readme, re.MULTILINE):
        readme_status[int(m.group(1))] = "✅" in m.group(2)
    if not readme_status:
        fail(name, "no milestone table rows parsed from README.md")
        return
    sections = re.split(r"^## Milestone (\d+)", roadmap, flags=re.MULTILINE)
    roadmap_complete = {}
    for i in range(1, len(sections), 2):
        num = int(sections[i])
        body = sections[i + 1].split("\n## ")[0]
        items = re.findall(r"^- \[([ xX])\]\s", body, re.MULTILINE)
        if items:
            roadmap_complete[num] = all(c.lower() == "x" for c in items)
    for num, complete in readme_status.items():
        if complete and num in roadmap_complete and not roadmap_complete[num]:
            fail(name, f"README marks Milestone {num} complete, but ROADMAP has "
                       "unchecked item(s) in that milestone")
    for ln in roadmap.splitlines():
        if re.match(r"^- \[", ln) and not re.match(r"^- \[[ xX]\]\s", ln):
            fail(name, f"malformed ROADMAP checkbox: {ln.strip()[:60]}")


# ---------------------------------------------------------------------------
# 6. Bug ledger integrity
# ---------------------------------------------------------------------------
BUG_STATUSES = {"open", "confirmed", "fixed", "wontfix", "rejected", "duplicate",
                "cannot-reproduce"}   # `rejected`: an unsubstantiated report (ledger README, #242)
BUG_SEVERITIES = {"low", "medium", "high", "critical"}
BUG_REPORTERS = {"internal", "third-party"}
BUG_REQUIRED = ("id", "title", "status", "severity", "reporter", "discovered")


def _parse_frontmatter(text):
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    fields = {}
    for line in text[3:end].splitlines():
        if not line.strip() or ":" not in line:
            continue
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    return fields


def check_bugs():
    name = "bugs"
    bugs_dir = os.path.join(ROOT, "docs", "bugs")
    if not os.path.isdir(bugs_dir):
        return
    index_path = os.path.join(bugs_dir, "README.md")
    index = read("docs", "bugs", "README.md") if os.path.exists(index_path) else ""
    numbers = []
    for cur, _d, files in os.walk(bugs_dir):
        for fn in files:
            m = re.fullmatch(r"BUG-(\d{4})-[a-z0-9-]+\.md", fn)
            if not m:
                continue
            num = int(m.group(1))
            rel = os.path.relpath(os.path.join(cur, fn), bugs_dir).replace(os.sep, "/")
            fm = _parse_frontmatter(read("docs", "bugs", *rel.split("/")))
            if fm is None:
                fail(name, f"{rel}: missing or malformed YAML frontmatter")
                continue
            for key in BUG_REQUIRED:
                if not fm.get(key):
                    fail(name, f"{rel}: missing required frontmatter key '{key}'")
            if fm.get("id") != f"BUG-{m.group(1)}":
                fail(name, f"{rel}: frontmatter id '{fm.get('id')}' != filename BUG-{m.group(1)}")
            if fm.get("status") and fm["status"] not in BUG_STATUSES:
                fail(name, f"{rel}: unknown status '{fm['status']}'")
            if fm.get("severity") and fm["severity"] not in BUG_SEVERITIES:
                fail(name, f"{rel}: unknown severity '{fm['severity']}'")
            if fm.get("reporter") and fm["reporter"] not in BUG_REPORTERS:
                fail(name, f"{rel}: unknown reporter '{fm['reporter']}'")
            disc = fm.get("discovered", "")
            dm = re.fullmatch(r"(\d{4})-(\d{2})-\d{2}", disc)
            if not dm:
                fail(name, f"{rel}: discovered '{disc}' is not YYYY-MM-DD")
            elif f"{dm.group(1)}/{dm.group(2)}/" not in rel:
                fail(name, f"{rel}: path does not match discovered date {disc}")
            if fm.get("status") == "fixed" and not fm.get("fixed-in"):
                fail(name, f"{rel}: status 'fixed' requires a 'fixed-in' release")
            if f"({rel})" not in index:
                fail(name, f"{rel} is not linked from docs/bugs/README.md index")
            numbers.append(num)
    if numbers:
        if len(set(numbers)) != len(numbers):
            fail(name, "duplicate BUG ids found")
        for i, n in enumerate(sorted(numbers), start=1):
            if n != i:
                fail(name, f"BUG numbering gap/dup: expected {i:04d}, found {n:04d}")
                break
    for link in re.findall(r"\]\((\d{4}/\d{2}/BUG-\d{4}-[a-z0-9-]+\.md)\)", index):
        if not os.path.exists(os.path.join(bugs_dir, link)):
            fail(name, f"index links missing bug file '{link}'")


# ---------------------------------------------------------------------------
# 7. i18n freshness (only when enabled)
# ---------------------------------------------------------------------------
def check_i18n_freshness():
    name = "i18n-freshness"
    if not CONFIG.get("i18n_enabled"):
        return
    manifest_rel = os.path.join("docs", "i18n", "translation-status.md")
    if not exists(manifest_rel):
        fail(name, f"i18n enabled but {manifest_rel} is missing")
        return
    manifest = read("docs", "i18n", "translation-status.md")
    i18n_dir = os.path.join(ROOT, "docs", "i18n")
    for line in manifest.splitlines():
        if not line.lstrip().startswith("| ["):
            continue
        if "`translated`" not in line:
            continue
        link = re.search(r"\]\(([^)]+)\)", line)
        sha = re.search(r"\|\s*`([0-9a-f]{7,40})`\s*\|", line)
        if link is None or sha is None:
            fail(name, f"could not parse translated manifest row: {line.strip()}")
            continue
        src = os.path.normpath(os.path.join(i18n_dir, link.group(1)))
        rel = os.path.relpath(src, ROOT).replace(os.sep, "/")
        newer = git("log", "--oneline", f"{sha.group(1)}..HEAD", "--", rel)
        if newer is None:
            fail(name, f"git unavailable or commit {sha.group(1)} not in history for {rel}")
        elif newer:
            fail(name, f"i18n translation of {rel} is STALE ({len(newer.splitlines())} "
                       "commit(s) after the recorded source commit)")


# ---------------------------------------------------------------------------
# 8. Enterprise posture ↔ compliance register (ADR-0015 / #248)
# ---------------------------------------------------------------------------
# The posture must not be prose-only. If AGENTS.md declares the enterprise posture, the
# compliance register (docs/compliance/README.md) must exist; and the register must not exist
# without the declaration. Two directions so neither the doc nor the AGENTS.md clause can drift
# out on its own — the same both-ways discipline the ADR-index and bug-ledger checks use.
_ENTERPRISE_MARKER = "enterprise governance posture"


def check_posture():
    name = "posture"
    agents = read("AGENTS.md") if exists("AGENTS.md") else ""
    declared = _ENTERPRISE_MARKER in agents
    register = exists("docs/compliance/README.md")
    if declared and not register:
        fail(name, "AGENTS.md declares the enterprise governance posture but "
                   "docs/compliance/README.md (the control register) is missing")
    if register and not declared:
        fail(name, "docs/compliance/README.md exists but AGENTS.md does not declare the "
                   "enterprise governance posture — the register has no posture to serve")


# ---------------------------------------------------------------------------
# 9. JPMS congruence (ITEM 1.6)
# ---------------------------------------------------------------------------
# The module descriptors and the POMs state the SAME dependency graph — ADR-001 / spec §3 — in two
# languages. Nothing else compares them: Maven resolves `<dependency>`, javac resolves `requires`,
# and a module that declares one without the other still compiles today. It breaks later, in the
# module that finally writes an import, which is the worst possible moment to discover it.
#
# So this check derives artifact -> module-name from the module-info files THEMSELVES rather than
# hardcoding a list of names. A hardcoded list would be a third statement of the same fact and would
# drift in its turn; deriving it means a module can be renamed in one place and the graph is still
# verified. What is asserted is the shape, not the names:
#
#   * every jar module in the reactor has a module-info.java (the BOM must NOT have one)
#   * module names are unique and live under the it.d4np.utils family root (ADR-0005)
#   * the INTERNAL `requires` edges equal the internal `<dependency>` entries, exactly
#
# Only internal (it.d4np) edges are compared. Third-party artifacts have no mechanically derivable
# module name (jackson-databind -> com.fasterxml.jackson.databind), so demanding a match there would
# invent failures the moment a real dependency lands.
_FAMILY_ROOT = "it.d4np.utils"


def _strip_java_comments(text):
    """Remove block and line comments before the graph is parsed out.

    No current descriptor needs this — verified, not assumed. It guards a hazard the descriptors'
    own house style invites: they discuss future clauses in prose, and one line of Javadoc reading
    `{@code requires java.sql;}` parses as a real edge against the raw text, so the lint would
    compare a graph nobody wrote and fail on a comment. Cheap here, confusing to diagnose later.
    """
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", "", text)


def check_jpms():
    name = "jpms-congruence"
    parent = os.path.join(ROOT, "pom.xml")
    if not os.path.exists(parent):
        return  # no reactor yet; item 1.1 owns that
    ns = {"m": "http://maven.apache.org/POM/4.0.0"}
    modules = [
        el.text.strip()
        for el in ET.parse(parent).getroot().findall("m:modules/m:module", ns)
    ]
    if not modules:
        fail(name, "the parent pom.xml declares no <modules>")
        return

    declared = {}  # artifactId -> module name
    internal_deps = {}  # artifactId -> set of internal artifactIds
    for mod in modules:
        pom = os.path.join(ROOT, mod, "pom.xml")
        if not os.path.exists(pom):
            fail(name, f"reactor module {mod} has no pom.xml")
            continue
        root = ET.parse(pom).getroot()
        artifact = (root.findtext("m:artifactId", namespaces=ns) or mod).strip()
        packaging = (root.findtext("m:packaging", default="jar", namespaces=ns)).strip()
        mi = os.path.join(ROOT, mod, "src", "main", "java", "module-info.java")

        if packaging == "pom":
            # The BOM: no sources, so a descriptor is impossible, not merely unnecessary.
            if os.path.exists(mi):
                fail(name, f"{mod} is packaging=pom yet ships {mod}/src/main/java/module-info.java")
            continue

        if not os.path.exists(mi):
            fail(name, f"{mod} is packaging={packaging} but has no src/main/java/module-info.java "
                       f"(spec §1.1: every module ships module-info)")
            continue

        body = _strip_java_comments(
            open(mi, encoding="utf-8").read()  # noqa: SIM115 - short-lived, read once
        )
        nm = re.search(r"\bmodule\s+([\w.]+)\s*\{", body)
        if nm is None:
            fail(name, f"{mod}/src/main/java/module-info.java declares no module name")
            continue
        module_name = nm.group(1)
        if module_name != _FAMILY_ROOT and not module_name.startswith(_FAMILY_ROOT + "."):
            fail(name, f"{mod} declares module `{module_name}`, which is outside the "
                       f"`{_FAMILY_ROOT}` family root (ADR-0005)")
        declared[artifact] = module_name

        requires = set(
            re.findall(r"\brequires\s+(?:(?:static|transitive)\s+)*([\w.]+)\s*;", body)
        )
        internal_deps[artifact] = {
            (d.findtext("m:artifactId", namespaces=ns) or "").strip()
            for d in root.findall("m:dependencies/m:dependency", ns)
            if (d.findtext("m:groupId", namespaces=ns) or "").strip() == "it.d4np"
        }
        # Stash the raw requires for the second pass, once every name is known.
        internal_deps[artifact] = (internal_deps[artifact], requires)

    dupes = {n for n in declared.values() if list(declared.values()).count(n) > 1}
    if dupes:
        fail(name, f"duplicate module name(s) across modules: {sorted(dupes)}")

    for artifact, (dep_artifacts, requires) in sorted(internal_deps.items()):
        expected = set()
        for dep in sorted(dep_artifacts):
            if dep not in declared:
                fail(name, f"{artifact} depends on it.d4np:{dep}, which declares no module name "
                           f"(is it packaging=pom, or missing a module-info.java?)")
                continue
            expected.add(declared[dep])
        actual_internal = {
            r for r in requires if r == _FAMILY_ROOT or r.startswith(_FAMILY_ROOT + ".")
        }
        if actual_internal != expected:
            missing = sorted(expected - actual_internal)
            extra = sorted(actual_internal - expected)
            detail = []
            if missing:
                detail.append(f"POM declares a dependency with no `requires`: {missing}")
            if extra:
                detail.append(f"`requires` with no POM dependency: {extra}")
            fail(name, f"{artifact}: module-info and pom.xml disagree — " + "; ".join(detail))


# ---------------------------------------------------------------------------
# 10. Every module carries a dependency policy (ITEM 1.7)
# ---------------------------------------------------------------------------
# NFR-08 is per-module by nature: core may not see Jackson, and d4np-json exists in order to see it.
# That means the framework-isolation rules cannot live in the parent, and a module without its own
# `enforce-adr-001` execution therefore has NO dependency policy at all — while still building green,
# because the parent's universal rules pass. A new module added in M2-M7 would inherit that silence.
#
# So this asserts the presence of the execution, not its contents. Judging the contents would mean
# re-encoding ADR-001 here, and a policy restated in two places drifts; the rules' correctness is
# established by the negative-test matrix recorded in ADR-0006 instead.
_ENFORCER_EXEC_ID = "enforce-adr-001"


def check_enforcer():
    name = "module-dependency-policy"
    parent = os.path.join(ROOT, "pom.xml")
    if not os.path.exists(parent):
        return
    ns = {"m": "http://maven.apache.org/POM/4.0.0"}
    proot = ET.parse(parent).getroot()

    # The parent owns the family-wide rules; without them FR-25 and the javax ban are unpoliced.
    ptext = read("pom.xml")
    if "enforce-universal" not in ptext:
        fail(name, "the parent pom.xml declares no `enforce-universal` enforcer execution, so the "
                   "family-wide rules (FR-25 test-scope ban, javax EE ban) do not run")

    for mod in [el.text.strip() for el in proot.findall("m:modules/m:module", ns)]:
        pom = os.path.join(ROOT, mod, "pom.xml")
        if not os.path.exists(pom):
            continue  # jpms-congruence already reports a missing module POM
        root = ET.parse(pom).getroot()
        if (root.findtext("m:packaging", default="jar", namespaces=ns)).strip() == "pom":
            # The BOM has no dependencies of its own to police, and carries no parent by design
            # (ADR-001/NFR-09), so it could not inherit the plugin even if it did.
            continue
        ids = [
            e.findtext("m:id", namespaces=ns)
            for e in root.findall(
                "m:build/m:plugins/m:plugin/m:executions/m:execution", ns
            )
        ]
        if _ENFORCER_EXEC_ID not in ids:
            fail(name, f"{mod} declares no `{_ENFORCER_EXEC_ID}` enforcer execution, so ADR-001's "
                       f"framework-isolation rules are not enforced for it (NFR-08)")


# ---------------------------------------------------------------------------
# 11. The NFR harnesses are wired to something (ITEM 1.8)
# ---------------------------------------------------------------------------
# This check exists because of a defect it would have caught two milestones earlier: ci.yml has been
# running `mvn -B -Pjmh verify` and `mvn -B -Pjcstress verify` since the scaffold render while
# NEITHER PROFILE EXISTED, and Maven only WARNS on an unmatched profile. Both jobs therefore reported
# a green performance and concurrency gate having measured nothing at all.
#
# Two things are asserted, and neither is a restatement of the POM:
#
#   * the parent declares both profiles, so the commands CI runs resolve to something;
#   * per module, owning harness sources and opting the runner in are the SAME fact. JMH and jcstress
#     both exit non-zero on an empty test list, so the parent defaults both switches to skip and a
#     module opts in beside its sources. That leaves two ways to be silently wrong — sources with no
#     opt-in (never measured, green) and an opt-in with no sources (fails the build for the wrong
#     reason) — and this asserts the bijection in both directions.
#
# What is NOT asserted: whether a given NFR has a harness yet. Most do not (M2-M6 own them), and a
# check that demanded one per NFR would have to be disabled today, which is how gates die.
_HARNESSES = (("jmh", "src/bench/java"), ("jcstress", "src/jcstress/java"))


def check_harness_opt_in():
    name = "harness-opt-in"
    parent = os.path.join(ROOT, "pom.xml")
    if not os.path.exists(parent):
        return
    ns = {"m": "http://maven.apache.org/POM/4.0.0"}
    proot = ET.parse(parent).getroot()

    profiles = {
        (el.findtext("m:id", default="", namespaces=ns)).strip()
        for el in proot.findall("m:profiles/m:profile", ns)
    }
    for profile, _root in _HARNESSES:
        if profile not in profiles:
            fail(name, f"the parent pom.xml declares no `{profile}` profile, but CI runs "
                       f"`mvn -B -P{profile} verify` — Maven only warns on an unmatched profile, so "
                       f"that job would pass having measured nothing")

    for mod in [el.text.strip() for el in proot.findall("m:modules/m:module", ns)]:
        pom = os.path.join(ROOT, mod, "pom.xml")
        if not os.path.exists(pom):
            continue  # jpms-congruence already reports a missing module POM
        mroot = ET.parse(pom).getroot()
        for profile, src_root in _HARNESSES:
            src_dir = os.path.join(ROOT, mod, *src_root.split("/"))
            has_sources = any(
                fn.endswith(".java")
                for _c, _d, files in os.walk(src_dir)
                for fn in files
            )
            opted_in = (
                mroot.findtext(f"m:properties/m:{profile}.skip", namespaces=ns) or ""
            ).strip() == "false"
            if has_sources and not opted_in:
                fail(name, f"{mod} owns {src_root} sources but does not set "
                           f"<{profile}.skip>false</{profile}.skip>, so `-P{profile}` compiles them "
                           f"and never runs them")
            if opted_in and not has_sources:
                fail(name, f"{mod} sets <{profile}.skip>false</{profile}.skip> but owns no "
                           f"{src_root} sources — the runner will fail on an empty test list")


# ---------------------------------------------------------------------------
# 12. The claimed static analysis is actually wired (ITEM 1.11)
# ---------------------------------------------------------------------------
# AGENTS.md §9/§10, the rendered spec, the PR template and the CI job title have all named
# "ErrorProne + NullAway" and "warnings-as-errors" since the scaffold, while the POM configured
# neither — the toolchain description was a claim about a build that did not make it. This check
# closes that gap in BOTH directions: a claim must be backed by configuration, and configuration
# must be reflected in the claim, so neither side can drift out on its own.
#
# What is asserted is the part that can fail SILENTLY. The three javac flags ErrorProne needs on
# JDK 21+ and the generated-sources exclusion are deliberately not checked here: dropping any of them
# fails the build immediately and by name (verified — "The default compilation policy (by-todo) is
# not supported by Error Prone", "-XDaddTypeAnnotationsToSymbol=true is required by Error Prone on
# JDK 21", and 12 ThreadPriorityCheck findings in JMH-generated code). A loud failure needs no lint.
# Severity and warnings-as-errors are the opposite case: demote NullAway to WARNING, or delete
# failOnWarning, and every finding still prints while the build turns green.
_CLAIM_KEYS = ("linter", "sanitizers")


def _strip_xml_comments(text):
    """Drop XML comments before the POM is matched for configuration.

    Not defensive: the first draft of this check read `AnnotatedPackages` out of the very comment
    that EXPLAINS the option, so deleting the option left the check green. The parent POM documents
    every knob it sets, which makes prose-matching a systematic false negative here rather than an
    edge case.
    """
    return re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)


def check_static_analysis():
    name = "static-analysis-wired"
    if not exists("pom.xml") or not exists("orchestrator/project.yaml"):
        return
    pom = _strip_xml_comments(read("pom.xml"))
    manifest = read("orchestrator", "project.yaml")
    claims = " ".join(
        m.group(1)
        for key in _CLAIM_KEYS
        for m in re.finditer(rf'^\s*{key}:\s*"([^"]*)"', manifest, re.MULTILINE)
    )
    for tool, claimed, wired, evidence in (
        (
            "ErrorProne",
            "ErrorProne" in claims,
            "-Xplugin:ErrorProne" in pom
            and "<artifactId>error_prone_core</artifactId>" in pom,
            "`-Xplugin:ErrorProne` plus an error_prone_core annotationProcessorPath",
        ),
        (
            "NullAway",
            "NullAway" in claims,
            "<artifactId>nullaway</artifactId>" in pom and "-Xep:NullAway:" in pom,
            "a nullaway annotationProcessorPath and its -Xep options",
        ),
    ):
        if claimed and not wired:
            fail(name, f"orchestrator/project.yaml claims {tool} in its toolchain description, but "
                       f"pom.xml does not configure it ({evidence} is missing) — the claim is then a "
                       f"review promise, which is what item 1.11 removed")
        if wired and not claimed:
            fail(name, f"pom.xml configures {tool} but the manifest's toolchain description no "
                       f"longer names it, so the generated docs under-report the quality bar")

    if "<artifactId>nullaway</artifactId>" in pom:
        if "-Xep:NullAway:ERROR" not in pom:
            fail(name, "NullAway is wired but not promoted to ERROR — at WARNING severity a "
                       "nullability finding prints and the build still passes")
        if (
            "-XepOpt:NullAway:AnnotatedPackages=" not in pom
            and "-XepOpt:NullAway:OnlyNullMarked" not in pom
        ):
            fail(name, "NullAway is wired with neither AnnotatedPackages nor OnlyNullMarked, so it "
                       "has no code to consider annotated")

    agents = read("AGENTS.md") if exists("AGENTS.md") else ""
    if "warnings-as-errors" in agents and "<failOnWarning>true</failOnWarning>" not in pom:
        fail(name, "AGENTS.md promises warnings-as-errors but pom.xml does not set "
                   "<failOnWarning>true</failOnWarning> on maven-compiler-plugin")


# ---------------------------------------------------------------------------
# 13. One specification authority (ITEM 1.12 / ADR-0010)
# ---------------------------------------------------------------------------
# Two documents described the same product and neither was subordinate to the other: the imported
# v2.0 draft in .spec/ and the rendered docs/specs/ spec. ROADMAP's own traceability section named the
# DRAFT as the FR/NFR id source — and the draft contains no FR- ids at all (measured: 0 FR, 6 NFR),
# because that vocabulary was minted during intake. ADR-0010 settles the ladder: an RFC outranks the
# spec where it pins a contract; the manifest's `spec.*` block is the source of record; the rendered
# spec is its authoritative published VIEW; the imported draft is superseded provenance.
#
# This check makes the ladder mechanical instead of prose:
#
#   * the manifest and the rendered spec carry the SAME FR/NFR ids, with the same requirement text —
#     the spec is generated from the manifest, so a hand-edit of the generated file is a divergence
#     that the next re-render silently reverts (risk R-07, which already cost item 1.4's work once);
#   * every FR/NFR id cited in ROADMAP.md exists in the manifest, so a roadmap item cannot invent a
#     requirement (or carry a typo) that no specification states;
#   * the superseded draft still says it is superseded, so the archive cannot quietly become a rival
#     source again.
_SPEC_VIEW = ("docs", "specs", "01_spec_utils.md")
_SPEC_DRAFT = (".spec", "d4np-java.md")
_SUPERSEDED_MARKER = "SUPERSEDED"


def _req_lines(text, prefix):
    """Requirement lines keyed by id, from either the manifest (quoted) or the rendered spec (bullet)."""
    out = {}
    for m in re.finditer(rf'^\s*-\s*"?({prefix}-\d+)\s+([^"\n]+?)"?\s*$', text, re.MULTILINE):
        out.setdefault(m.group(1), m.group(2).strip())
    return out


def check_spec_authority():
    name = "spec-authority"
    if not exists("orchestrator/project.yaml") or not exists("/".join(_SPEC_VIEW)):
        return
    manifest = read("orchestrator", "project.yaml")
    view = read(*_SPEC_VIEW)

    for prefix in ("FR", "NFR"):
        src, pub = _req_lines(manifest, prefix), _req_lines(view, prefix)
        if not src:
            fail(name, f"orchestrator/project.yaml declares no {prefix}-NN requirement lines, so the "
                       f"rendered spec has no source of record (ADR-0010 rung 2)")
            continue
        missing = sorted(set(src) - set(pub))
        extra = sorted(set(pub) - set(src))
        if missing:
            fail(name, f"{prefix} id(s) in the manifest but not in {'/'.join(_SPEC_VIEW)}: {missing} — "
                       f"the published spec is stale; re-render it from the manifest")
        if extra:
            fail(name, f"{prefix} id(s) in {'/'.join(_SPEC_VIEW)} but not in the manifest: {extra} — "
                       f"the spec was hand-edited, and the next re-render will delete this (R-07)")
        for rid in sorted(set(src) & set(pub)):
            if src[rid] != pub[rid]:
                fail(name, f"{rid} text differs between the manifest and the published spec — edit the "
                           f"manifest and re-render, never the generated file")

    # No roadmap item may cite a requirement the specification does not state.
    if exists("ROADMAP.md"):
        known = set(_req_lines(manifest, "FR")) | set(_req_lines(manifest, "NFR"))
        cited = set(re.findall(r"\b(?:FR|NFR)-\d+\b", read("ROADMAP.md")))
        dangling = sorted(cited - known)
        if dangling:
            fail(name, f"ROADMAP.md cites requirement id(s) that no specification states: {dangling}")

    # The superseded draft must keep saying so.
    if exists("/".join(_SPEC_DRAFT)):
        draft = read(*_SPEC_DRAFT)
        if _SUPERSEDED_MARKER not in draft:
            fail(name, f"{'/'.join(_SPEC_DRAFT)} no longer carries its {_SUPERSEDED_MARKER} banner, so "
                       f"the intake draft reads as a live specification again (ADR-0010 rung 3)")
        if re.search(r"\bFR-\d+\b", draft):
            fail(name, f"{'/'.join(_SPEC_DRAFT)} now contains FR- ids — the superseded draft is being "
                       f"maintained as a rival requirement source (ADR-0010 rejected exactly that)")


CHECKS = [
    check_version_lockstep,
    check_adr_index,
    check_patterns,
    check_spec_map,
    check_milestones,
    check_bugs,
    check_i18n_freshness,
    check_posture,
    check_jpms,
    check_enforcer,
    check_harness_opt_in,
    check_static_analysis,
    check_spec_authority,
]


def main():
    for fn in CHECKS:
        try:
            fn()
        except Exception as exc:  # a check crashing is itself a failure
            fail(fn.__name__, f"check crashed: {exc!r}")
    if failures:
        print("Consistency lint: FAIL\n")
        for check, message in failures:
            print(f"  [{check}] {message}")
        print(f"\n{len(failures)} congruence problem(s) found.")
        return 1
    print("Consistency lint: OK — all congruence invariants hold.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
